# Generated by Django 4.2.7 on 2024-02-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_amount_alter_payment_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
