# Generated by Django 4.2.7 on 2024-02-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_subscription_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='owner',
        ),
    ]
